version: '3.8'
services:
  db:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INTIDB_ROOT_USERNAME=root
      - MONGO_INTIDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    restart: unless-stopped
  web:
    build: ./Streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - db
    restart: unless-stopped

